name: Node.JS CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: node:lts-alpine

  steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

